(in-package #:cl-game-models)

(defun load-mtl (file)
  (format t "--- inside load-mlt ~A ~%" file)
  (let ((lines (file-lines file))
	(materials (make-hash-table :test #'equal))) 
     (do ((n 0 (+ n 1)))
	 ((= n (length lines)))
       (let ((line (nth n lines)))
	 (if (new-mtl? line)
	   (let ((key (parse-new-mtl line)))
	     (format t "----> Loading a new material at line .... ~A ~%" n)
	     (do ((i (+ n 1) (+ i 1)))
		 ((cond ((new-mtl? (nth i lines))
			 (setf i (- n 1))
			 t) ; reset pointer back so we don't miss next material
			((= i (length lines))
			 t)
			(t nil)))
	       (let ((line (nth i lines)))
		 (cond ((map-kd? line)
			(format t " Adding map-kd .... ~A ~%" i)
			(setf (gethash key materials) 
			      (file-namestring (parse-map-kd line))))
		       (t nil))))))))
      materials))
