;;;; package.lisp

(defpackage #:cl-game-models
  (:use #:cl #:opticl #:cxml)
  (:export #:load-mesh
	   #:load-anim
	   #:load-obj
	   #:load-atlas-obj
	   #:load-mtl
	   #:load-dae
	   #:build-all-frame-skeletons
	   #:md5anim-frame-rate
	   #:md5anim-njoints
	   #:md5anim-nframes
	   #:anim-info
	   #:anim-max-time
	   #:animate
	   #:anim-curr-frame
	   #:anim-next-frame
	   #:anim-curr-frame-block
	   #:anim-max-frame-blocks
	   #:anim-last-time
           #:mesh
	   #:md5mesh
	   #:mesh-shader
	   #:mesh-vertices
	   #:mesh-archive-info
	   #:test-archive
	   #:archive-scene-objects
	   #:archive-primitive-objects
	   #:clean-archive-dir
	   #:mesh-frames
	   #:mesh-gl-vertices
	   #:mesh-gl-indices
	   #:mesh-gl-texels
	   #:mesh-indices-length
	   #:tex-u
           #:tex-v
	   #:vertex-texuv
	   #:vertex-pos
	   #:coerce-array-to-list
	   #:interpolate-skeletons
	   #:frame-joints
	   #:joint-position
	   #:vec-x
	   #:vec-y
	   #:vec-z
	   #:joint-parent-id
	   #:meshes-list
	   #:meshes-count
	   #:mesh-name
	   #:mesh-axis-box
	   #:prepare-mesh
	   #:prepare-mesh2
	   #:prepare-all-meshes
	   #:prepare-all-meshes2
	   #:prepare-all-md5-vertex-meshes
	   #:compute-stroke-trajectory
	   #:compute-stroke-trajectory2
	   #:compute-stroke-trajectory3
	   #:compute-bowling-trajectory
	   #:compute-bowling-trajectory2
	   #:compute-bowling-trajectory3
	   #:md5anim-frames
	   #:load-texture
	   #:mesh-texture
	   #:mesh-texture-key
	   #:mesh-nvertices
	   #:mesh-vbo-buffers
	   #:mesh-texture-buffers
	   #:mesh-texture-id
	   #:mesh-texture-buffer-id
	   #:mesh-vertex-buffer-id
	   #:mesh-index-buffer-id
	   #:texture-texels
	   #:texture-width
	   #:texture-height
	   #:make-vector
	   #:make-anim-info
	   #:make-lines-mesh
	   #:make-camera
	   #:make-camera-position
	   #:make-frustum
	   #:point-in-frustum
	   #:prepare-axis-box
	   #:build-axis-box
	   #:build-wfaxis-box
	   #:min-box
	   #:max-box
	   #:boxes-intersect?
	   #:get-full-path
 	   #:make-scene-object 	   
 	   #:make-scene-object-with-lattice
 	   #:make-scene-object-with-textures-map
 	   #:make-primitive-scene-object 	   
 	   #:build-vertex-frames
  	   #:add-vertex-frames
	   #:make-md5-vertex-scene-object	  
	   #:make-md5-scene-object
	   #:build-frame-block
	   #:add-pose-frames
	   #:move-to-next-frame-block
	   #:update-anim-info
	   #:clear-scene-objects
	   #:find-scene-object
	   #:find-primitive-object
	   #:find-dynamic-primitive-object
	   #:remove-primitive-object
	   #:remove-scene-object
	   #:add-event-handler
	   #:handle-event
	   #:add-frames
	   #:add-frame-block
	   #:add-scene-object
	   #:add-scene-light
	   #:add-primitive-object	   
	   #:add-dynamic-primitive-object	   
	   #:update-dynamic-primitive-object	   
	   #:change-dynamic-primitive-object-visibility
	   #:change-scene-object-visibility
	   #:change-dynamic-primitive-object-sound-status
	   #:specify-scale
	   #:specify-rotation
	   #:specify-translation
	   #:specify-translation-deltas
	   #:specify-delta-fn
	   #:specify-frame-fn
	   #:apply-translation-deltas
	   #:initialize-anim-info
	   #:find-mesh
	   #:find-curr-mesh-frame
	   #:make-scene
	   #:make-light
	   #:make-material
	   #:scene-object-name
	   #:scene-object-meshes
	   #:scene-object-rotation
	   #:frame-block-event
	   #:frame-block-event-fn
	   #:scene-object-scale
	   #:scene-object-translation
	   #:scene-object-delta-fn
	   #:scene-object-frame-fn
	   #:scene-object-translation-deltas
  	   #:scene-object-anim-info
	   #:scene-object-frames
	   #:frame-block-start-frame
	   #:frame-block-end-frame
	   #:scene-object-frame-blocks
	   #:scene-object-nframes
	   #:init-opengl
	   #:render-scene-objects
	   #:render-scene-object
	   #:render-primitive-object
	   #:load-textures
	   #:load-scene-object-buffers
	   #:load-primitive-object-buffers
	   #:scene-objects
	   #:primitive-objects
	   #:dynamic-primitive-objects
	   #:gl-vertexes
           #:gl-indexes
           #:gl-texels
           #:make-gl-unsigned-int-vector
           #:make-gl-single-vector
           #:start-animation-with-vsync
           #:stop-animation-with-vsync
	   #:event-handlers
	   #:build-trajectory-vertex-frames
	   #:add-trajectory-frames
	   #:update-frame-block-transformations
	   #:make-camera-perspective
	   #:make-camera-view
	   #:make-scene-camera
	   #:add-scene-camera
	   #:assign-current-camera
	   #:get-scene-camera
	   #:change-camera-perspective
	   #:change-camera-perspective-fovy
	   #:change-camera-view
	   #:change-camera-view-eye
	   #:change-camera-view-center
	   #:angle->radians
	   #:radians->angle
	   #:initialize-scene
	   #:initialize-a-scene-object
	   #:initialize-a-primitive-object
	   #:get-scene-world
	   #:initialize-scene-world
	   #:resize-canvas
	   #:redisplay-canvas
	   #:group
	   #:filter
	   #:file-lines))
